### ISSUE TITLE
Menus cannot be built if one of the projects is damaged

### ISSUE THREAD

**Issue by xcaeag** [aeag/MenuFromProject-Qgis-Plugin#125]
### What is the bug or the crash?

A ‘faulty’ project stops the menus from loading.
This is a project containing a ‘ghost’ layer, which only appears in the legend, but is not in the XML tree structure of the ‘projectlayers’.

ex : [projet-ko.zip](https://github.com/user-attachments/files/17932694/projet-ko.zip)

### Steps to reproduce the issue

use this project in the plugin configuration

### Versions

3.34

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the official roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

in the `project_read.py` script, I propose to catch the exception when calling `get_layer_menu_config`, and to move on to the next layer.

**Comment by jmkerloch** [comment]
I managed to reproduce the error with the provided qgs.

I will make the code more robust for this kind of error.

@xcaeag how did you managed to have this damaged project ?

**Comment by xcaeag** [comment]
I don't know! It was an old project...

**Comment by haubourg** [comment]
Hhhaaa the famous 250 layers project with ghost layers that made QGIS so unhappy! 
Good old times.

Cheers from the Alps Xavier. I hope Pyrénées are going well !

**Comment by xcaeag** [comment]
salut l'ami, 
avec le gros travail accompli par les deux forçats, tu ne vas pas en revenir, les gros projets foireux ne font plus peur au plugin !
Et les Pyrénées sont de plus en plus belles !
