### ISSUE TITLE
Python error on unload

### ISSUE THREAD

**Issue by nicogodet** [aeag/MenuFromProject-Qgis-Plugin#136]
### What is the bug or the crash?

```sh
TypeError: 'method' object is not connected 
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 545, in unloadPlugin
    plugins[packageName].unload()
  File "C:\Users/godet/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\menu_from_project\menu_from_project.py", line 426, in unload
    self.iface.initializationCompleted.disconnect(self.on_initializationCompleted)
TypeError: 'method' object is not connected
```

### Steps to reproduce the issue

I didn't find a way to reproduce on each time... Sorry :( 

On my plugin, I wrap signal disconnections in suppress() context:

```python
from contextlib import suppress

class MyPlugin:
    [...]

    def unload(self):
        [...]

        with suppress(AttributeError, RuntimeError, TypeError):
            self.object.disconnect(self.method)
```

### Versions

3.40.1 OSgeo4W

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the official roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Guts** [comment]
Thank you @nicogodet for taking time to report!

To be sure I understand well. The Menu Layers From Project crashes because of another plugin you maintain?

Why do you need to suppress those Exceptions? As written in [official python documentation](https://docs.python.org/fr/3.12/library/contextlib.html#contextlib.suppress), it's kinda rough and should be used in fully controlled execution environment which is really complicated in QGIS wih every plugins using the same Python environment.

**Comment by nicogodet** [comment]
I'm not sure why this happen.

> The Menu Layers From Project crashes because of another plugin you maintain?

It happens when I tried to update this plugin from BETA2 to 2.2.0 stable.

I updated to 2.2.0 stable, use Plugin Reloader to reload the plugin (just because I wanted to) and
```sh
TypeError: 'method' object is not connected 
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 545, in unloadPlugin
    plugins[packageName].unload()
  File "C:\Users/godet/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\menu_from_project\menu_from_project.py", line 421, in unload
    self.action_project_configuration.triggered.disconnect(
TypeError: 'method' object is not connected
```

> Why do you need to suppress those Exceptions?

Because if disconnect fails it's not a huge deal and it's safe to continue and not raise an exception.  
I saw few plugins where disconnect is wrapped in try/except (which is equivalent to with suppress().

**Comment by jmkerloch** [comment]
I didn't reproduce this error but I guess we can be more defensive for this disconnection. If it fails it doesn't matter.

@Guts  is it OK for you to add `with suppress(AttributeError, RuntimeError, TypeError)` ?

**Comment by nicogodet** [comment]
TypeError would be enough I guess for disconnect. I don't recall why I add Attribute and Runtime...

**Comment by Guts** [comment]
I don't reproduce it neither. @nicogodet can you try again on a fresh profile please?

**Comment by nicogodet** [comment]
Got it... Issue comes from another plugin which calls `initializationCompleted.disconnect()` without specifying method so disconnect all methods including ones from other plugins.

I fixed it on my plugin so it won't interfere with others anymore. 
Feels free to close.

**Comment by Guts** [comment]
Thanks @nicogodet for taking time to report and following up here with your feedback, really appreciated!
