### ISSUE TITLE
Layers menu not showing up on QGIS 3.28

### ISSUE THREAD

**Issue by mjmolivo** [aeag/MenuFromProject-Qgis-Plugin#137]
### What is the bug or the crash?

Hello, as some coworkers told me, the layers menu doesn't show up when using QGIS version 3.28 ltr. The project has been saved as PostgreSQL project. No error message appearing, and the extension menu seems to work alright. Only the project is not appearing on the menu bar.
Everything is fine on the 3.34 ltr however.

### Steps to reproduce the issue

Hard to reproduce the issue without any further informations...

### Versions

Version de QGIS | 3.28.8-Firenze | Révision du code | 5ac45272b5
-- | -- | -- | --
Version de Qt | 5.15.3
Version de Python | 3.9.5
Version de GDAL/OGR | 3.7.0
Version de Proj | 9.2.1
Version de la base de données du registre EPSG | v10.088 (2023-05-13)
Version de GEOS | 3.11.2-CAPI-1.17.2
Version de SQLite | 3.41.1
Version de PDAL | 2.5.3
Version du client PostgreSQL | unknown
Version de SpatiaLite | 5.0.1
Version de QWT | 6.1.6
Version de QScintilla2 | 2.13.1
Version de l'OS | Windows 10 Version 2009
  |   |   |  
Extensions Python actives
AdressesFr | 1.1
autoSaver | 2.9
BioDispersal | 1.3
cartogram3 | 3.1.5
GroupStats | 2.2.7
lizmap | 4.4.6
mask | 1.10.4
MemoryLayerSaver | 5.0.2
mmqgis | 2024.11.8
pcraster_tools | 0.3.0
processing_saga_nextgen | 1.0.0
QGIS3-getWKT | 1.6
qgisgbifapi | 0.3.4
QuickWKT | 3.1
quick_map_services | 0.19.36
shapefile_encoding_fixer | 0.7.1
SpreadsheetLayers | 2.1.2
SRTM-Downloader | 3.2.3
valuetool | 3.0.19
db_manager | 0.1.20
MetaSearch | 0.3.6
otbprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99
menu_from_project | 2.2.0

</body></html>Version de QGIS
3.28.8-Firenze
Révision du code
[5ac45272b5](https://github.com/qgis/QGIS/commit/5ac45272b5)
Version de Qt
5.15.3
Version de Python
3.9.5
Version de GDAL/OGR
3.7.0
Version de Proj
9.2.1
Version de la base de données du registre EPSG
v10.088 (2023-05-13)
Version de GEOS
3.11.2-CAPI-1.17.2
Version de SQLite
3.41.1
Version de PDAL
2.5.3
Version du client PostgreSQL
unknown
Version de SpatiaLite
5.0.1
Version de QWT
6.1.6
Version de QScintilla2
2.13.1
Version de l'OS
Windows 10 Version 2009

Extensions Python actives
AdressesFr
1.1
autoSaver
2.9
BioDispersal
1.3
cartogram3
3.1.5
GroupStats
2.2.7
lizmap
4.4.6
mask
1.10.4
MemoryLayerSaver
5.0.2
mmqgis
2024.11.8
pcraster_tools
0.3.0
processing_saga_nextgen
1.0.0
QGIS3-getWKT
1.6
qgisgbifapi
0.3.4
QuickWKT
3.1
quick_map_services
0.19.36
shapefile_encoding_fixer
0.7.1
SpreadsheetLayers
2.1.2
SRTM-Downloader
3.2.3
valuetool
3.0.19
db_manager
0.1.20
MetaSearch
0.3.6
otbprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99
menu_from_project
2.2.0

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the official roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by jmkerloch** [comment]
Thanks for the report !

There is an issue on QGIS 3.28.x because we are now using [`userProfileManager`](https://qgis.org/pyqgis/3.34/gui/QgisInterface.html#qgis.gui.QgisInterface.userProfileManager) to download project and save cache of project parsing.

We need to adapt the code to be able to run on 3.28.x.

I will try to do fix soon.

**Comment by Guts** [comment]
Released as part of version 2.2.1:

- https://plugins.qgis.org/plugins/menu_from_project/version/2.2.1/
- https://github.com/aeag/MenuFromProject-Qgis-Plugin/releases/tag/2.2.1
