### ISSUE TITLE
Delete menu doesn't work

### ISSUE THREAD

**Issue by naub1n** [aeag/MenuFromProject-Qgis-Plugin#138]
### What is the bug or the crash?

When I delete menu in LMFP configuration and I restart QGIS, my menu still exists in configuration.

### Steps to reproduce the issue

1. Check QGIS Options before adding menu in LMFP
![image](https://github.com/user-attachments/assets/5bce4fc1-46f9-445f-820a-f8867721c779)
2. Add menu TEST
![image](https://github.com/user-attachments/assets/fd116f83-dba2-488d-8e16-b948a053c4ba)
3. Check in QGIS Options : OK
![image](https://github.com/user-attachments/assets/9b354ee3-a6ac-4ae2-9701-6f0fa93c6c8a)
4. Delete menu TEST
![image](https://github.com/user-attachments/assets/3dbf4cf1-935e-47da-9710-83f0fc7d5def)
5. Check in QGIS Options : KO - Menu still exists:
![image](https://github.com/user-attachments/assets/cfee57b2-d85d-4962-bbc8-7bd8c56ae9fe)

### Versions

QGIS : 3.37.7
LMFP : 2.2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the official roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by xcaeag** [comment]
Bonjour Nicolas,

après qq tests : il semble que ce soit le script spécifique "Agences de l'eau" qui soit à l'origine du pb. startup.py n'est pas adapté au nouveau plugin (fonction set_menu_from_project_config qui change la configuration).

Pour parcourir un 'tableau', j'utilise plutôt `beginReadArray` et non `beginGroup`... mais cela ne suffira peut être pas, les paramètres liés au cache sont à prendre en compte aussi...

**Comment by naub1n** [comment]
@xcaeag , le problème est également présent sur un profil hors ceux de la DSIUN pour lequel le script de démarrage de la DSIUN ne fait rien.
Je vais tester sur mon PC Perso au cas où.

Edit: Après un test sur mon poste perso. Le comportement est identique coté options de QGIS mais le menu ne s'affiche pas dans LMFP alors qu'il est présent dans les options.

**Comment by naub1n** [comment]
J'ai trouvé le problème.
L'option _size_ est diminuée de 1 dans les options sans que le sous-dossier des projets soit supprimé.
Du coup, mon script de démarrage compte les projets existants et remets la valeur à "réelle". Le projet réapparait ensuite dans LMFP.

**English**
_size_ option in QGIS Settings (menu_from_project > projects > size) is decrease by 1 but project directory still exists.
My startup script count projects and so, set "real" value to _size_ option.

**Comment by xcaeag** [comment]
Parfait.
à faire aussi : faire suivre les nouveaux paramétrages (..\cache_config) ?

**Comment by jmkerloch** [comment]
@naub1n Il y a du coup un problème dans le plugin ou dans le script de démarrage ?

Je vais voir pour reproduire le problème cet après midi.

**Comment by jmkerloch** [comment]
J'ai pu reproduire le bug ou les projets supprimés sont toujours présents dans le fichier QGIS3.ini

En fait il n'y avait aucun problème à la lecture car le champ `size` est lu lors de la lecture de la liste des projets. On n'utilise donc pas les projets qui avaient été supprimés.

MAIS comme il y a une modification du fichier .ini avant le démarrage dans le script de @naub1n , le paramètre `size` est remplacé avec la taille de TOUT les projets disponibles. Et du coup les projets supprimés réapparaissent.

@naub1n  je suis surpris que ce problème n'arrive que sur cette version 2.2.0.

J'ai pu faire une PR pour corriger ce problème #139

**Comment by naub1n** [comment]
@xcaeag , `beginWriteArray` a un fonctionnement qui lui est propre et je comprend mieux pourquoi tu indiquais d'utiliser la fonction `beginReadArray`.
Ce fonctionnement entraine du stockage inutile de config dans les settings de QGIS.

Cela dit, je vais faire évoluer mon script pour utiliser la fonction `beginReadArray` pour calculer la longueur de la liste.
Le petit ajout de @jmkerloch permettra quant à lui d'optimiser les éléments stockés dans les settings de QGIS.

Merci à vous deux !

**Comment by Guts** [comment]
Correction intégrée à la version 2.2.1 publiée ce jour :

- https://plugins.qgis.org/plugins/menu_from_project/version/2.2.1/
- https://github.com/aeag/MenuFromProject-Qgis-Plugin/releases/tag/2.2.1
