### ISSUE TITLE
using dash at beginning of layer name

### ISSUE THREAD

**Issue by Gustry** [aeag/MenuFromProject-Qgis-Plugin#16]
I didn't read carefully the code but I noticed this line:
https://github.com/xcaeag/MenuFromProject-Qgis-Plugin/blob/master/menu_from_project/menu_from_project.py#L339

I didn't see this tip in the documentation. Is-it to put a layer in bold if it starts by a dash?
I tried, it didn't work.

**Comment by xcaeag** [comment]
For exemple (a folder named "-XXX") :

![menu](https://user-images.githubusercontent.com/7790344/52567589-0253a700-2e0d-11e9-847b-c26a63d97472.png)

**Comment by Gustry** [comment]
Your bold is on a "group", right?.
And you make an empty group with bold to build a kind of header?

I tried the dash on a layer, I think I didn't see the difference.
Docs needs some update on the area.

**Comment by xcaeag** [comment]
Yes that's it.
A small gif shows this in the wiki.

**Comment by Gustry** [comment]
I never noticed the wiki.
There is a few documentation : readme.md, HTML pages in the git repo and wiki. Can we maybe just make one documentation? and add links to the main unique documentation?

It's difficult to maintain 3 of them and I never notice the wiki. Can we switch to markdown file in git?

**Comment by Gustry** [comment]
I noticed you removed the documentation in the readme.

Thanks for your work.
