### ISSUE TITLE
Layer doesn't appear when sourced from "Integrate layers and group"

### ISSUE THREAD

**Issue by 4estone** [aeag/MenuFromProject-Qgis-Plugin#20]
When I get a source .qgs build on layers and groups from others .qgs and loaded with "Integrate layers an groups" only layers inside a firstlevel group are displayed in the menu. The n+1 groups ans layers above first group are not displayed.

**Comment by xcaeag** [comment]
Indeed, an untested case. I
see if the fix is possible.

**Comment by xcaeag** [comment]
a version 1.0.3 will be tested when it will be published!

**Comment by 4estone** [comment]
Hi,
After migratiging from 3.16 to 3.28.7 I get same problem than previously. Menu only display first group level from qgs source. No error messages, no clue ...

**Comment by xcaeag** [comment]
version 2.1.0 should correct the problem.
be careful, there is no longer the 'v' in front of the version number, you may need to uninstall the plugin first.

**Comment by 4estone** [comment]
Thanks. Everythink is ok. No problem to install new plugin release.
