### ISSUE TITLE
use the custom labels of qgz files?

### ISSUE THREAD

**Issue by FERRATON** [aeag/MenuFromProject-Qgis-Plugin#22]
Maybe related to #7
Currently the plugin does not retrieve custom labels stored in qgz.

**Comment by xcaeag** [comment]
And it works with a .qgs? It seems like no.
Data that allows labels management is stored in an append SQLITE database.
It becomes a bit difficult to pick them up, bring them back to the current project ...
That goes beyond my skills !

**Comment by FERRATON** [comment]
That's a pity. The underlying problem is the ability to store custom labels in a layer style.
I'll make a request in the QGIS tracker.
