### ISSUE TITLE
[Feature] Add an option to concatenate projects to the previous menu

### ISSUE THREAD

**Issue by haubourg** [aeag/MenuFromProject-Qgis-Plugin#27]
Hi!
Some users would like to be able to concatenate some project files into one project. 

I believe we could concatenate a project to the project above in the list. 

Let's see if we get some support to make this happen.

**Comment by xcaeag** [comment]
Hi,
it's an idea, why not! I'm going to try !

bonne rentrée(s) !

**Comment by xcaeag** [comment]
To test !
The option is a new item in the 'location' list (in the configuration window)

**Comment by haubourg** [comment]
\o/ merci Xavier!  (There was no obligation to have you do it )

**Comment by BrunoDefrance** [comment]
Merci Xavier ! 
Ça fonctionne nickel !

**Comment by xcaeag** [comment]
Quelques lignes ont suffi, cela n'a pas été trop douloureux. Et la fonctionnalité nous dépanne bien aussi ! Merci pour l'idée.
