### ISSUE TITLE
[Feature] Allow pointing to http/https online qgs-qgz project file

### ISSUE THREAD

**Issue by haubourg** [aeag/MenuFromProject-Qgis-Plugin#28]
Hi Toulouse, Chartreuse speaking !

We are on our way to submit a PR adding a new feature. The idea would be to allow to fetch the qgs project from a http-https adress to solve use cases where there is no shared directory or database. 

The first requirement will be to make sure to use native QgsNetwork settings and classes, so that proxies and agent are respected. 

Authentication is not required for the first iteration. 

@xcaeag have you ever faced this need or have any advice here? (please let us do the code part ;-) )

**Comment by xcaeag** [comment]
Hello mountaineer,

We haven't had any such needs, but it's a good idea! this opens up interesting possibilities.
and if you want to redesign the configuration interface ... go !

I add a dev branch ?

**Comment by haubourg** [comment]
Cool! 

> I add a dev branch ?

no need, we will submit the branch from a fork somewhere .

**Comment by Guts** [comment]
# Proposition détaillée

L'intégration de cette nouvelle fonctionnalité implique de modifier le comportement de l'interface, donc voici une proposition avant de pousser le code.

Je rédige en français. Au besoin, je traduirai en anglais.

On considère un utilisateur qui dispose de plusieurs projets QGS/Z.

## Parcours utilisateur actuel

> voir aussi [le wiki](https://github.com/xcaeag/MenuFromProject-Qgis-Plugin/wiki#comment-lutiliser-)

1. Il lance le plugin `Extensions > Layers menu from project > configurer les projets`
2. il clique sur le bouton `+` --> une ligne s'ajoute au tableau
3. il clique sur le bouton `...` et va sélectionner son projet QGS/Z via l'explorateur de fichiers ou colle une chaîne de connexion à une base PG
 
## Parcours proposé

1. Il lance le plugin `Extensions > Layers menu from project > configurer les projets`
2. au clic sur le bouton `+` : petit menu déroulant proposant les 3 options d'ajouts :
  - fichier -> ouvre le sélecteur de fichier qgs/z actuel
  - base de données -> mini-prompt pour entrer la chaîne de connexion
  - url -> idem que pour les bases mais des validateurs de texte différents

### Conséquences

- la colonne `...` disparaît au profit d'un bouton d'édition (icône crayon proposée)

### Remarques diverses

- prévoir les cas de timeouts et proxys, etc...
- les boutons actuels sont des `QToolButton` et peuvent être déclassés en `QPushButton`
- la chaîne de connexion à une base devrait être remplacée par le choix parmi les connexions déjà établies - évolution future à prévoir et à spécifier. En attendant, masquer les parties "sensibles" (user/mdp) à l'affichage ?

**Comment by xcaeag** [comment]
Tout ceci me semble bien. Je suis prêt à tester petit à petit.. et répondre aux questions si il y en a sur le code pas toujours très propre !
Concernant la connexion aux bases, nous n'avons pas ici utilisé cette fonctionnalité, laissée de coté. Elle mérite en effet des améliorations.

**Comment by haubourg** [comment]
> base de données -> mini-prompt pour entrer la chaîne de connexion

+1. Ne pas oublier de pouvoir déléguer à un fichier de service.  

> la chaîne de connexion à une base devrait être remplacée par le choix parmi les connexions déjà établies - évolution future à prévoir et à spécifier. En attendant, masquer les parties "sensibles" (user/mdp) à l'affichage ?

A discuter, c'est pénible dans QGIS de devoir sortir de son workflow pour devoir créer la connexion, puis revenir dessus. 

> la chaîne de connexion à une base devrait être remplacée par le choix parmi les connexions déjà établies - évolution future à prévoir et à spécifier. En attendant, masquer les parties "sensibles" (user/mdp) à l'affichage ?

Pas forcément. En tout cas la partie base de données n'est pas dans le cadre de la PR sur la partie web. 

Enfin sur la technique, je pense qu'il faut prévoir un cache local du dernier projet récupéré, en cas de problème réseau sur l'adresse web. C'est peut-être le plus pénible ici
