### ISSUE TITLE
Plugin stops to work in some configurations

### ISSUE THREAD

**Issue by laurentbre** [aeag/MenuFromProject-Qgis-Plugin#3]
Hi,

Environment: Windows 8.1 64.
Layers menu from project version: 0.7.6

In some configurations the plugin stops to work : click on the menu to add a layer does not load it (There is a message "Menu from layer : invalid C:/Users/laurent.breton/Documents/Temp/menu-geoportail_test2_2.18.qgs" in the plugin tile log)
It can occur with 2.18.1, 2.18.3 standard install or 2.12 French Ministry of Environment specific package.
Delete the profile directory makes the plugin work again.
Disable the other plugins does not change anything

Here is a simple project I used to test, with a WMS layer (same problem with a local shapefile layer).
[menu-geoportail_test2_2.18.qgs.zip](https://github.com/xcaeag/MenuFromProject-Qgis-Plugin/files/1431104/menu-geoportail_test2_2.18.qgs.zip)

**Comment by xcaeag** [comment]
Hi,

I can not reproduce the problem.
The easiest way to progress is that you contact me (?).
- Xavier Culos - at the phone number you will find at the bottom of the page : http://www.eau-adour-garonne.fr

**Comment by xcaeag** [comment]
Incompatible with the plugin "qgis2compat", which overwrites the "qgis.core.QgsProject.read" method.
Do not use with "qgis2compat".
