### ISSUE TITLE
v1.2.0-beta1 - Error with network drive resolver

### ISSUE THREAD

**Issue by Guts** [aeag/MenuFromProject-Qgis-Plugin#37]
Une erreur lié à notre architecture peut être : l'appel à Path.resolve() provoque une erreur lorsque le répertoire est un répertoire réseau, sur lequel on peut écrire pourtant.

>>> dir = Path('f:/')
>>> dir.resolve()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "W:\OSGeo4W64\apps\Python37\lib\pathlib.py", line 1123, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "W:\OSGeo4W64\apps\Python37\lib\pathlib.py", line 189, in resolve
    s = self._ext_to_normal(_getfinalpathname(s))
PermissionError: [WinError 5] Accès refusé: 'f:\\'

**Comment by xcaeag** [comment]
Il me semblait qu'il ne manquait pas grand chose pour aboutir et publier une nouvelle version ?
Si j'enlève l'appel à resolve(), tout fonctionne ici sous windows ou linux.

**Comment by Guts** [comment]
Bonne idée @xcaeag ! Dans ce cas, je te laisse faire cette modification ?

Je pense qu'on peut publier une version avec le flag experimental histoire de collecter des retours sans émeute ;).
Il reste quand même que le sélecteur pointe sur l'explorateur de fichiers, même pour les bases et URLs. Mais c'est pas bloquant et je devrais pouvoir dégager du temps dans quelques temps pour soigner ça.

Etapes de release (en vue de les mettre dans la doc à un moment) :

- [ ] compléter le fichier changelog.md (dans un monde idéal, la release est faite avec qgis-plugin-ci qui met à jour automatiquement le metadata.txt à partir de ce fichier, mais bon ça demande de configurer des secrets toussa)
- [ ] passer le flag experimental à True
- [ ] changer le numéro de version dans le fichier __about__ et tagger le commit correspondant


Pour le numéro de version, peut-être passer à 2 histoire de respecter semver ? genre 2.0.0-beta1 ?

**Comment by xcaeag** [comment]
Ah oui, le sélecteur...  c'est vrai.. bon, pourquoi pas une beta tout de même.
J'explore petit à petit les nouveautés que tu as apporté, merci @Guts. Bientôt qgis-plugin-ci !

**Comment by Guts** [comment]
> pourquoi pas une beta tout de même.

Surtout qu'à partir de QGIS 3.14, le gestionnaire d'extensions gère la possibilité d'installer une version expérimentale beaucoup plus facilement.

> J'explore petit à petit les nouveautés que tu as apporté, merci @Guts.

Et les bugs introduits ;) ! De rien, content que ça te plaise et merci d'avoir accueilli mes contributions.

> Bientôt qgis-plugin-ci !

En fait, c'est déjà utilisé. Il reste pas grand chose poour automatiser la publication.


Question subsidiaire : du coup, tu fonctionnes par par git tag @xcaeag pour numéroter les versions ?

**Comment by xcaeag** [comment]
oui, j'ai vu que qgis-plugin-ci travaillait déjà.. je vais explorer ça.
git tag, non, pas plus que ça. Tu vois bien que je ne maitrise pas trop l'environnement. Git n'était qu'un espace de stockage et de partage jusque là.

**Comment by Guts** [comment]
> oui, j'ai vu que qgis-plugin-ci travaillait déjà.. je vais explorer ça.

Sinon, un tuto ne devrait plus tarder sur un certain site ;)

> git tag, non, pas plus que ça. Tu vois bien que je ne maitrise pas trop l'environnement. Git n'était qu'un espace de stockage et de partage jusque là.

Pas de souci, je suis pas non plus un git-god of war. En gros, git tag c'est ce qui sert à étiqueter un commit dans l'historique avec un nom, typiquement le numéro de version. Et c'est ce qui est sous-jacent aux "releases" des surcouches telles que GitHub/Gitlab etc.
