### ISSUE TITLE
Incompatibility with the plugin ProfilTool

### ISSUE THREAD

**Issue by EricLazzaretti** [aeag/MenuFromProject-Qgis-Plugin#4]
Hi,
like with the plugin QGis2compat, MenuFromProject seems to not be compatible with the plugin ProfilTool.
The layer are not loaded. The code stop at "QgsProject.instance().read(node)" without error.

**Comment by xcaeag** [comment]
Fixed in ProfilTool : https://github.com/PANOimagen/profiletool/commit/ab84c2a26781c52d683dd933ac8bcba468603efb
