### ISSUE TITLE
v1.2.0-beta1 - Ordonnancement des projets dans l'interface de configuration

### ISSUE THREAD

**Issue by xcaeag** [aeag/MenuFromProject-Qgis-Plugin#40]
Le déplacement "vers le haut" ne fait pas remonter l'icône (type de source)
Le déplacement "vers le bas" ne fait pas descendre l'îcone, ni la source

**Comment by Guts** [comment]
En y regardant de plus près, je me demande si ce serait pas plus rentable d'activer le déplacement par drag'n drop intégré à Qt ? 

Quelque chose comme :

```python
self.tableWidget.verticalHeader().setSectionsMovable(True)
self.tableWidget.verticalHeader().setDragEnabled(True)
self.tableWidget.verticalHeader().setDragDropMode(QAbstractItemView.InternalMove)
```

**Comment by xcaeag** [comment]
Oui, bien sûr, à tester. On peut conserver les boutons malgré tout ? Faire attention à l'option 'Ajouter au précédent' si l'item passe en première position.

**Comment by Guts** [comment]
Hmmm je préfère garder que les boutons alors pour la prochaine version.

**Comment by xcaeag** [comment]
Ok, c'est le genre de chose que je pourrai faire plus tard...

**Comment by Guts** [comment]
C'était finalement plus galère que prévu, il y a un crash de QGIS (de Qt en fait) lorsque que l'on re set un pixmap qui est une image non compilée (ici l'icône globe).

Du coup, j'ai refacto la façon de générer l'icône et le bouton d'édition en passant par des méthodes dédiées. Finalement c'est pas plus mal, ça centralise leur configuration, mais c'est peut-être moins lisible.
