### ISSUE TITLE
v1.2.0-beta1 - Traduction de l'interface de configuration

### ISSUE THREAD

**Issue by xcaeag** [aeag/MenuFromProject-Qgis-Plugin#41]
Manque la version Française aux Items du menu "ajouter une couche"

**Comment by Guts** [comment]
@xcaeag une raison pour ne pas stocker le fichier de gestion des traducitons (*.pro) mais stocker les traductions compilées (*qm) ?

Je sais que ça permet de ne pas avoir à installer les outils Qt liés (lrelease) dans la CI mais pour un plugin relativement petit et qui n'utilise pas transifex (ou autre), le fichier pro est plutôt pratique et git est plus fait pour les fichiers texte et non binaires (ce qu'est le fichier qm).

**Comment by xcaeag** [comment]
Aucune raison valable non, du travail de néophyte.

**Comment by Guts** [comment]
Ok alors j'ai proposé un compromis :

- ajout du fichier .pro
- conservation du *.qm

Pour mémo, le workflow de traduction :

1. on marque les textes à traduire dans le code avec self.tr (ou self.plugin.tr) et dans les fichiers d'interface via la case idoine
2. on génère les fichiers de traduction avec pylupdate (si on a jouté de nouvelles sources, mettre à jour le fichier pro avt) :
  
  ```bash
  pylupdate5 -noobsolete -verbose menu_from_project/plugin_translation.pro 
  ```
3. on traduit (soit éditeur de texte, soit qt linguist)
4. on compile les traductions 

  ```bash
  lrelease -compress menu_from_project/i18n/fr.ts
  ```

**Comment by xcaeag** [comment]
Merci !
