### ISSUE TITLE
Load above in ToC

### ISSUE THREAD

**Issue by katagen** [aeag/MenuFromProject-Qgis-Plugin#48]
Hi,
First of all, thank you very much for this plugin. It works great, easy to use and speed up my workflow.

I just have a question: when I select a new layer in my menus, it loads always under the layers already loaded. Is it possible to load them above?

For exemple, I first load some raster for my working area, to see where I am. Then I load some vectors, but they are under my rasters, why is not really logical. And if I load some new vectors, they are under the vectors already present. For me, it seems more logical that the last loaded vectors are above, at least the group they belong to.

Thank you for your answer!

**Comment by xcaeag** [comment]
Thank you for your remark,

it seems that this happens when the creation of 'groups' is enabled. Otherwise, the new layer comes on top of the selected layer.
It is true that this is not nice, a fix may be in a future version !

**Comment by xcaeag** [comment]
Can you try this experimental version : 2.0.1-beta1 ?

**Comment by katagen** [comment]
Hello,
So it works perfectly for me! I didn't test everything, but I try the menus I already had, and all the layers work and load above in the ToC, or in the group they belong to...

It's perfect for me, thank you very much!!!
