### ISSUE TITLE
Alternatively use metadata as tooltip instead of OGC metadata

### ISSUE THREAD

**Issue by haubourg** [aeag/MenuFromProject-Qgis-Plugin#50]
Hi! 
QGIS now has a proper metadata section in the layer properties. We are starting to use them as our source of truth and source of harvesting for a CSW catalog. 
It would be nice if the tooltip could display this information instead of the old OGC metadata dedicated to QGIS server.  
I think this would be a per layer option to add.  

Being able to use an expression to build this tooltip would be even more crazy. I dream of being able of displaying title  + constraint aggregate + citations agregates .

**Comment by xcaeag** [comment]
Hi friend,
of course it's a good idea,
Do you have any leads on integrating expression into a plugin interface ? QgsExpressionBuilderDialog  ?
Is the "layer_property" function sufficient to build the tooltip ?
Are all metadata accessible from an expression ?
Will it be necessary to propose new variables ?

**Comment by xcaeag** [comment]
Il y a des choses à tester du coté de QgsExpressionLineEdit, mais...

Concernant les expressions, une des difficulté viendra du fait que les couches ne sont pas connues de QGis à la construction du menu. 
Une expression ne pourra pas être interprété dans un contexte 'layerScope'. A quoi peut ressembler alors une expression dans ce cas ?
A la construction du menu, on dispose 'seulement' d'un nœud DOM, on ne va tout de même pas proposer une syntaxe xpath ! Je ne vois pas de solution simple, générique. Une idée ?

**Comment by haubourg** [comment]
>  A la construction du menu, on dispose 'seulement' d'un nœud DOM, on ne va tout de même pas proposer une syntaxe xpath ! Je ne vois pas de solution simple, générique. Une idée ?

Hello, et bien vu, effectivement je ne vois pas de solution. Ce n'est pas très important cette histoire d'expression, oublie!

**Comment by xcaeag** [comment]
que penses-tu, pour faire simple, en attendant de trouver mieux, de proposer ce choix là  ? De privilégier soit une source, soit l'autre ?

![image](https://user-images.githubusercontent.com/7790344/130047484-20ce7431-4449-4cc0-986f-f4ca22d9a5ab.png)

ou plus simple
![image](https://user-images.githubusercontent.com/7790344/130048691-e6e7e0dd-3da6-4822-ae1e-cfc1f48c968a.png)

**Comment by haubourg** [comment]
Je serais preneur de quelquechose proche de la première version, avec un texte comme ça: 

[ v ] Afficher titre et résumé.  <spacer>  Source des métadonnées : (o) métadonnées OGC QGIS server    ( ) métadonnées de la couche

Qu'est-ce que tu en penses?

**Comment by xcaeag** [comment]
C'est mieux, oui. C'est tout simple, et j'ai un peu de temps ! 
Un système de template serai bien, mais je n'arrive pas à trouver une idée propre. On va laisser murir.

**Comment by xcaeag** [comment]
Un paquet en test ici si tu as le temps..

[menu_from_project-latest.zip](https://github.com/xcaeag/MenuFromProject-Qgis-Plugin/files/7029687/menu_from_project-latest.zip)
