### ISSUE TITLE
I would like to translate this plugin into Japanese.

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [aeag/MenuFromProject-Qgis-Plugin#63]
Nice to meet you.
I would like to translate this plugin into Japanese.
I can use Qt Linguist.
Is it correct to create ja.ts and modify pro?
Implementation is scheduled for today or next weekend.

**Comment by xcaeag** [comment]
hello, 

yes, of course, glad to see the plugin live!

I'm not a translation specialist, and I work with .pro and .ts files, the "pylupdate" tool and compile with "lrelease" to produce .qm.

a .ts is perfect, with modification of the .pro indeed.
you can send me the files or issue a pull-request, as you prefer..

**Comment by yamamoto-ryuzo** [comment]
Thank you for your reply.
I will send you the .pro and .ts files as soon as they are completed.

**Comment by yamamoto-ryuzo** [comment]
https://github.com/xcaeag/MenuFromProject-Qgis-Plugin/pull/64
