### ISSUE TITLE
Vectortiles get corrupted if added to a map

### ISSUE THREAD

**Issue by bru500** [aeag/MenuFromProject-Qgis-Plugin#77]
When adding a vectortile to a menu, it gets corrupted when added via plugin. It seems to be added as a wrong type:  the added layer has the icon of a vectorlayer instead of vectortile, and an unavailable datasource.

Example: 
1. Add the following vectortile service to a map: https://vectortiles.geo.admin.ch/tiles/ch.swisstopo.leichte-basiskarte.vt/v2.0.0/{z}/{x}/{y}.pbf
2. Put it in a Menu
3. Add it to a map
-> The Layer has an unavailable record source and the wrong icon.

**Comment by xcaeag** [comment]
In which version of the plugin and of QGis are you working?
In QGis 3.28, plugin 2.0.6, the layer is well interpreted, like a vector tile layer...

![image](https://user-images.githubusercontent.com/7790344/231464622-3631704d-3325-4e9d-bdf9-87e298c3bd9f.png)

**Comment by bru500** [comment]
Sorry for the delay and thanks for checking.
I'm on QGIS 3.28.4 with Layers menu from project 2.0.6 on windows 10.
In the Menu, the vectortile has the correct item as in your screenshot:
![2023-04-22 12_33_26-QGIS3](https://user-images.githubusercontent.com/40229231/233778814-3c615663-0b74-4e0e-ba04-3cf942dca5e5.png)
But when it, it apperas in the Layers panel, it gets the wrong icon and an unavailable datasource:
![2023-04-22 12_34_37-_2_Schweiz — QGIS](https://user-images.githubusercontent.com/40229231/233779088-77f00b87-5ced-44d7-b319-3218c354407e.png)
### Different datasource
Interesting, that the original layer and the one created by the plugin have different datasources:
original: 
`styleUrl=https://vectortiles.geo.admin.ch/styles/ch.swisstopo.leichte-basiskarte-imagery.vt/style.json&type=xyz&url=https://vectortiles.geo.admin.ch/tiles/ch.swisstopo.leichte-basiskarte.vt/v2.0.0/%7Bz%7D/%7Bx%7D/%7By%7D.pbf&zmax=14&zmin=0&http-header:referer=`
created by plugin: 
`styleUrl=https://vectortiles.geo.admin.ch/styles/ch.swisstopo.leichte-basiskarte.vt/style.json&type=xyz&url=https://vectortiles.geo.admin.ch/tiles/ch.swisstopo.leichte-basiskarte.vt/v2.0.0/%7Bz%7D/%7Bx%7D/%7By%7D.pbf&zmax=14&zmin=0&http-header:referer=`
In the styleURL the part "-imagery.vt" is missing.
### Demo project
I created a simple demo project. The qgz-FIle was used to create a menu from itself. One layer was created manualy and the other by the plugin: [menu.zip](https://github.com/xcaeag/MenuFromProject-Qgis-Plugin/files/11301129/menu.zip)
I hope this helps to clarify. Thank's for the great plugin!
Bruno

**Comment by xcaeag** [comment]
good news, the problem is reproduced, but it is not solved yet !

It occurs when the 'create a group' checkbox is checked, it works better otherwise.

I will try to understand the phenomenon.

**Comment by xcaeag** [comment]
v2.0.7 to be tested 
thank you for reporting this bug

**Comment by bru500** [comment]
Thank you! I can confirm, that the bug is fixed.
